# Ques1  Create a NumPy array from a Python list and print its shape and datatype.

In [1]:
import numpy as np

# Create a Python list
py_list = [1, 2, 3, 4, 5]

# Convert list to NumPy array
arr = np.array(py_list)

# Print the array
print("Array:", arr)

# Print the shape of the array
print("Shape:", arr.shape)

# Print the datatype of the array
print("Data type:", arr.dtype)


Array: [1 2 3 4 5]
Shape: (5,)
Data type: int64


# Ques 2  Create a 2D array of size 4x4 filled with random numbers.

In [7]:
import numpy as np

# Create a 4x4 array with random numbers between 0 and 1
arr = np.random.rand(4, 4)

print("4x4 Random Array:\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


4x4 Random Array:
 [[0.96902356 0.90611699 0.28835019 0.80403477]
 [0.27568543 0.3126417  0.24437708 0.28490196]
 [0.56709815 0.35500029 0.10519755 0.6640446 ]
 [0.13276524 0.46745508 0.49176473 0.18340505]]
Shape: (4, 4)
Data type: float64


# Ques 3 Generate a NumPy array of 10 evenly spaced values between 1 and 100.

In [8]:
import numpy as np

# Generate 10 evenly spaced values between 1 and 100
arr = np.linspace(1, 100, 10)

print("Evenly spaced array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)


Evenly spaced array: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
Shape: (10,)
Data type: float64


# Ques 4 Perform addition, subtraction, and multiplication on two NumPy arrays.

In [9]:
import numpy as np

# Define two arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# Perform addition
add_result = arr1 + arr2

# Perform subtraction
sub_result = arr1 - arr2

# Perform multiplication
mul_result = arr1 * arr2

# Print results
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)


Array 1: [10 20 30 40]
Array 2: [1 2 3 4]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]


# Ques 5 Reshape a 1D NumPy array of 12 elements into a 3x4 matrix.

In [10]:
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(1, 13)   # [1, 2, 3, ..., 12]

# Reshape into 3x4 matrix
reshaped_arr = arr.reshape(3, 4)

print("Original 1D Array:", arr)
print("Reshaped 3x4 Matrix:\n", reshaped_arr)
print("Shape:", reshaped_arr.shape)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


# Ques 6 Calculate mean, median, and standard deviation of a NumPy array.

In [11]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Calculate statistics
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev = np.std(arr)

# Print results
print("Array:", arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)


Array: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


# Ques 7 Use slicing to extract a subarray from a larger 2D NumPy array.

In [12]:
import numpy as np

# Create a 4x5 array
arr = np.arange(1, 21).reshape(4, 5)  # numbers 1 to 20

print("Original 4x5 Array:\n", arr)

# Extract subarray (rows 1–2, columns 2–4)
sub_arr = arr[1:3, 2:5]

print("\nExtracted Subarray:\n", sub_arr)


Original 4x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Extracted Subarray:
 [[ 8  9 10]
 [13 14 15]]


# Ques 8 Save a NumPy array to a .npy file and reload it.

In [13]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Save the array to a .npy file
np.save("my_array.npy", arr)

# Reload the array from the file
loaded_arr = np.load("my_array.npy")

print("Original Array:", arr)
print("Reloaded Array:", loaded_arr)


Original Array: [10 20 30 40 50]
Reloaded Array: [10 20 30 40 50]


# Ques 9 Demonstrate element-wise comparison operations in NumPy.

In [14]:
import numpy as np

# Define two arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([15, 20, 25, 40])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Element-wise comparisons
print("\nEqual (==):", arr1 == arr2)
print("Not Equal (!=):", arr1 != arr2)
print("Greater Than (>):", arr1 > arr2)
print("Less Than (<):", arr1 < arr2)
print("Greater or Equal (>=):", arr1 >= arr2)
print("Less or Equal (<=):", arr1 <= arr2)


Array 1: [10 20 30 40]
Array 2: [15 20 25 40]

Equal (==): [False  True False  True]
Not Equal (!=): [ True False  True False]
Greater Than (>): [False False  True False]
Less Than (<): [ True False False False]
Greater or Equal (>=): [False  True  True  True]
Less or Equal (<=): [ True  True False  True]


# Ques 10 Create an identity matrix using NumPy and display it.

In [15]:
import numpy as np

# Create a 4x4 identity matrix
identity_matrix = np.eye(4)

print("4x4 Identity Matrix:\n", identity_matrix)


4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
